### ISSUE TITLE
Integrazione Chatbot-Youtube

### ISSUE THREAD

**Issue by elisasorrentino** [vale17accidentidellastoria/SE2-Project#11]
User story: voglio poter cercare in youtube dei video chiedendo direttamente al chatbot.

HTD: scrivo al chatbot che voglio cercare su youtube "Mozart", nella parte sinistra della pagina propone i primi 4 video risultati dalla ricerca

User test:
scrivo nel chatbot "Voglio cercare su Youtube un video su pippo", nella parte sinistra della pagina vedo 4 video correlati

**Comment by wizofoz** [comment]
@elisasorrentino: Integrato ChatBot con la ricerca video su youtube ( [https://github.com/vale17accidentidellastoria/SE2-Project/commit/915089874e2cddddf9bb902631333b59549f89dd](https://github.com/vale17accidentidellastoria/SE2-Project/commit/915089874e2cddddf9bb902631333b59549f89dd) ), in attesa di addestramento del chatbot per poter scrivere: "Voglio cercare su Youtube un video.." e frasi simili.

**Comment by elisasorrentino** [comment]
aggiustato e chiuso
