### ISSUE TITLE
Integrazione ChatBot con il front-end React

### ISSUE THREAD

**Issue by elisasorrentino** [vale17accidentidellastoria/SE2-Project#13]
Il Chatbot deve essere in grado di interagire con il front-end in React scambiando informazioni

**Comment by wizofoz** [comment]
Added in commit: [https://github.com/vale17accidentidellastoria/SE2-Project/commit/915089874e2cddddf9bb902631333b59549f89dd](https://github.com/vale17accidentidellastoria/SE2-Project/commit/915089874e2cddddf9bb902631333b59549f89dd)
