### ISSUE TITLE
Componente per ricerca video

### ISSUE THREAD

**Issue by vale17accidentidellastoria** [vale17accidentidellastoria/SE2-Project#24]
Implementare un componente che permetta la ricerca di video su Youtube nel frontend

**Comment by wizofoz** [comment]
Added in commit [https://github.com/vale17accidentidellastoria/SE2-Project/commit/0005461cb2c170ac81ee9b812bbd2cb7c34e316f](https://github.com/vale17accidentidellastoria/SE2-Project/commit/0005461cb2c170ac81ee9b812bbd2cb7c34e316f)
