### ISSUE TITLE
Gestione della sessione

### ISSUE THREAD

**Issue by elisasorrentino** [vale17accidentidellastoria/SE2-Project#3]
**User story**: vorrei che il paziente possa vedere i contenuti multimediali condivisi su un altro schermo

**HTD**: accedo a Kioku, inserisco l'ID paziente, eseguo il login e grazie al Chatbot e alle funzionalità di condivisione multimediale, mi aspetto di poter condividere dei contenuti come video e canzoni. Il paziente se accede a Kioku da un'altro dispositivo e inserisce il suo ID, potrà visualizzare i contenuti che sono stati condivisi con lui fino a quel momento

**Comment by vale17accidentidellastoria** [comment]
Commit: [5163ac0029506dfa020d245c3e72078d9334d9da](5163ac0029506dfa020d245c3e72078d9334d9da)
