### ISSUE TITLE
Youtube search component is not displayed correctly

### ISSUE THREAD

**Issue by wizofoz** [vale17accidentidellastoria/SE2-Project#31]
Nell'ultimo commit lo stile di visualizzazione non si è mantenuto.

HTD: Come utente devo poter visualizzare i risultati con uno stile coerente a quello del resto della pagina

**Comment by vale17accidentidellastoria** [comment]
Fixing commit: [734ee0286b36e3fa4aa8348281c35b139413787b](https://github.com/vale17accidentidellastoria/SE2-Project/commit/734ee0286b36e3fa4aa8348281c35b139413787b)

**Comment by vale17accidentidellastoria** [comment]
Fixing commit: [734ee0286b36e3fa4aa8348281c35b139413787b](https://github.com/vale17accidentidellastoria/SE2-Project/commit/734ee0286b36e3fa4aa8348281c35b139413787b)
