### ISSUE TITLE
Addestramento del ChatBot

### ISSUE THREAD

**Issue by elisasorrentino** [vale17accidentidellastoria/SE2-Project#4]
**User story**: vorrei che il ChatBot mi fornisse diverse features in modo da essere di supporto nella terapia. Le funzionalità saranno:
* Santo del giorno
* chiedere aiuto
* tutorial
* Albero genealogico
* accedere a contenuti multimediali (video, canzoni, ...)
* scegliere l'argomento da trattare
* contatti degli sviluppatori

**HTD**: accedo a Kioku, inserisco l'ID del paziente, faccio il login e mi aspetto che il chatbot compaia sulla destra in modo da poter interagire con esso

**Comment by gianlucapessotto** [comment]
per la barzelletta siamo sicuri che c'entri con l'obiettivo dell'applicazione? Penso sia una di quelle feature aggiuntive che in realtà non servano

**Comment by vale17accidentidellastoria** [comment]
Ok, non c'entra con la reminiscenza il discorso delle barzellette. Però è sempre una feature in più che permette all'anziano di rapportarsi in maniera più "amichevole" al bot, per questo io penso che dovremmo lasciarla...

**Comment by elisasorrentino** [comment]
gians KISS man :) 
comuque dipende secondo me dallo scopo: forse aveva senso quando il bot si interfacciava con l'anziano perchè comunque dava un carattere al bot e alleggeriva magari in alcuni momenti. Visto che il bot deve essere di supporto ad un operatore/parente penso che sia lui a dover dare il giusto taglio alla conversazione, se vuole ci mette una battuta o una barzelletta o un racconto ma che sia aderente alla sua personalità.
non so se mi sono spiegata...
