### ISSUE TITLE
Pubblicazione su heroku del progetto

### ISSUE THREAD

**Issue by gianlucapessotto** [vale17accidentidellastoria/SE2-Project#41]
Rendere disponibile il progetto online

**Comment by elisasorrentino** [comment]
[heroku commit](https://github.com/vale17accidentidellastoria/SE2-Project/commit/38d2afb579311a2c4f7a0753b4ee6cf4ce078041)

[Heroku app](https://kiokuchatbot.herokuapp.com/)
