### ISSUE TITLE
Aiuti presenti nel front-end

### ISSUE THREAD

**Issue by wizofoz** [vale17accidentidellastoria/SE2-Project#49]
**User story:** la prima volta che accedo al sito voglio poter essere guidato alla prima esperienza con Kioku sul modo di procedere per loggarsi, interagire con il bot e condividere contenuti.

**HTD:** apro Kioku, inserisco l'ID del paziente e vedo un messaggio che mi da le informazioni iniziali per usare il sito

**Comment by vale17accidentidellastoria** [comment]
Commit: [29cc3a09ad0a867bdd2cf6f765795849bec74c51](29cc3a09ad0a867bdd2cf6f765795849bec74c51)
