### ISSUE TITLE
Albero genealogico

### ISSUE THREAD

**Issue by gianlucapessotto** [vale17accidentidellastoria/SE2-Project#7]
**User story:** vorrei, attraverso le informazioni raccolte dai discorsi con il paziente, ricostruire il suo albero genealogico, anche per poter stimolare la sua memoria

**HTD:** apro Kioku, inserisco l'ID paziente, faccio il login, chiedo al chatbot "Albero genealogico" in modo da ottenere degli spunti di conversazione sulla famiglia

**Comment by elisasorrentino** [comment]
[Albero genealogico](https://github.com/vale17accidentidellastoria/SE2-Project/commit/42475bf76653e721b9fda45e2e3420d2c3ed13e2)
